### ISSUE TITLE
[PhongTT] Dựng môi trường server K8s cho dự án

### ISSUE THREAD

**Issue by tuanvh-0174** [the-cev7/tlg-documents#2]
- Dựng môi trường server K8s cho dự án
Yêu cầu:
- Dựng môi trường có đầy đủ, nginx, web-server, crontjob, queuejob
- Có thiết lập autoscaling cho web-server

**Comment by phongtt-1837** [comment]
Report 26-03-2024:
Em đã deploy dc lên 1 pods mới của con dev calliope rồi
Em hiểu là bây giờ chỉ cần setting host ở file ingress là có thể kết nối được vào
Hiện tại thì phần code deploy chưa có gì cải tiến hơn so với phần đã có của con dev
Em đang nghiên cứu phần tạo thêm 1 pods nữa để đảm nhiệm phần cronjob

**Comment by phongtt-1837** [comment]
Pull:
https://github.com/framgia/automation-backend/pull/507

**Comment by dungda-0794** [comment]
đã có pull và đang review

**Comment by phongtt-1837** [comment]
Docs
https://github.com/the-cev7/tlg-documents/pull/27
