### ISSUE TITLE
DucPV] Sử dụng sun*CI xây dựng CI & CD cho dự án

### ISSUE THREAD

**Issue by tuanvh-0174** [the-cev7/tlg-documents#6]
- Sử dụng sunCI xây dựng CD cho dự án Liên quan tới Backend
Yêu cầu:
- deploy lên môi trường server của sun
- Tự động chạy deploy khi được merge vào branch develop

**Comment by ducpv-1644** [comment]
PR: https://github.com/the-cev7/nestjs-codebase/pull/17/files
đã test và đã delpoy thành công
